### ISSUE TITLE
New datasets from a new snowman version are not shown in the tool

### ISSUE THREAD

**Issue by Lasklu** [HPI-Information-Systems/snowman#63]
**Describe the bug**
The new [release](https://github.com/HPI-Information-Systems/snowman/releases/tag/v1.1.0) includes a new preloaded dataset. When the user already has a snowman version installed and now wants to update this version, he does not see the newly added dataset because the database will not be updated. Up to now he has to delete the whole database in ```AppData```.

**Expected behaviour**
Snowman should show every newly added dataset. For example, we should restart the database initialization process after installing a new version.

**Comment by florian-papsdorf** [comment]
Therefor we should think about how we want to organize patches, which data will how be migrated and does the user have to agree with a migration. Nevertheless, we have to pay attention not to create useless effort.

**Comment by martingraf4** [comment]
I would propose the following:

- with every release we prebuild the database folder for performance reasons. New installations will use this.
- additionally we preload all newly added preloaded content by specifically putting it into the migration script of the new version
  - we need to give all preloaded content IDs which are guaranteed to not be used when a user uploads an experiment / dataset / matching solution. Because otherwise we could accidentaly overwrite her/his content.
  - idea: give preloaded content negative ids?
- we should maybe also think about adding the preloaded content to the API spec as this might be of interest to the frontend (e.g. IDs of preloaded matching solutions)

**Comment by martingraf4** [comment]
Frontend uses "impossible dataset id" -1
