### ISSUE TITLE
Show complete error message on click

### ISSUE THREAD

**Issue by martingraf4** [HPI-Information-Systems/snowman#67]
Some times the error message is too large to be completely visible. We should allow the user to expand the error message.

![image](https://user-images.githubusercontent.com/49309285/109939418-53bf7f00-7cd1-11eb-8cae-16761a813ccd.png)

**Comment by phpfs** [comment]
It is not easily possible to show more text with a button. Instead, I opted for a better solution which will simply cause the text to be wrapped. In order for this work, I had to remove the small "x" button in the upper right corner of the toast. Since clicking the toast itself will dismiss it too, I'd say that this is a proper fix here :) What do you think @martingraf4 ?
![Screenshot 2021-03-04 142038](https://user-images.githubusercontent.com/15683974/109969977-d1e14d00-7cf4-11eb-874b-4f8dfaf0bf8c.png)

**Comment by martingraf4** [comment]
works for me
